### ISSUE TITLE
Civilization's rule book

### ISSUE THREAD

**Issue by nabil-alsabah** [phamdaniel/comp361#35]
Hi guys,

Great project! I would like to do a similar project using Swift 5.3. So my question: did you write down the rules of the game yourself based on your game knowledge? Or is there an official source that I can rely on?

Thanks,
Nabil

**Comment by danhp** [comment]
Hey @nabil-alsabah,
So this was actually a project done for a school project. Most of the rules we had to follow are in the `Informal project requirements` in README.md
Unfortunately we're not too versed in actual Civ so can't help too much on that front.

**Comment by nabil-alsabah** [comment]
Hi Daniel,

I see, thank you very much!

Best,
Nabil
